package com.example.TrelloClone.Services;


import com.example.TrelloClone.Helpers.History;
import com.example.TrelloClone.Helpers.Task;
import com.example.TrelloClone.Helpers.Task;
import com.example.TrelloClone.Repo.TaskDeleteRepository;
import com.example.TrelloClone.Repo.ModifyRepository;
import com.example.TrelloClone.Repo.TaskRepository;
import com.example.TrelloClone.Repo.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import javax.swing.text.html.parser.Entity;
import java.sql.Time;
import java.time.LocalTime;

@Service
public class MainService {
    @Autowired // This means to get the bean called taskRepository which is auto-generated by Spring, we will use it to handle the data
    private TaskRepository taskRepository;
    @Autowired
    private UserRepository userRepository;
    @Autowired
    private TaskDeleteRepository del;

    @Autowired
    private ModifyRepository modifyRepository;

    public String findByName(Long suid){
        return userRepository.findUserNameBySuid(suid);
    }

    public Iterable<Task> findAll(){
        return taskRepository.findAll();
    }

    public void save(Task s){
        taskRepository.save(s);
    }


    public Long findtaskID(Long id){
       return del.findTaskId(id);
    }

    public void deleteCommentById(Long taskID){
        del.deleteCommentsByTaskId(taskID);
    }

    public void deleteById(Long taskID){
        del.deleteTaskById(taskID);
    }

    public LocalTime fetchTime(Long id){
        return modifyRepository.fetchTimestamp(id);
    }

    public Long fetchTimeInTodo(Long id){
        return modifyRepository.fetchDurationInTodo(id);
    }

    public Long fetchTimeInDoing(Long id){
        return modifyRepository.fetchDurationInDoing(id);
    }

    public Long fetchTimeInDone(Long id){
        return modifyRepository.fetchDurationInDone(id);
    }
    public void updateTimestamp(Long id, Time time){
       modifyRepository.updateTaskTimestamp(id,time);
    }

    public void addCompletionTime(Long id, Long time){
        modifyRepository.updateCompletionTime(id,time);
    }

    public void timeInTodo(Long id, Long time){
        modifyRepository.updateTimeInTodo(id,time);
    }

    public void timeInDoing(Long id, Long time){
        modifyRepository.updateTimeInDoing(id,time);
    }

    public void timeInDone(Long id, Long time){
        modifyRepository.updateTimeInDone(id,time);
    }
    public void changestate(Long id,int state){
        modifyRepository.updateTaskState(id,state);
    }

    public void changeusername(Long id,Long newsuid){
        modifyRepository.updateTaskOwner(id,newsuid);
    }

    public void changename(Long id,String name){
        modifyRepository.updateTaskName(id,name);
    }

    public int getCurrentState(Long taskid){
        return modifyRepository.fetchCurrentState(taskid);
    }

    public void changedesc(Long id,String desc){
        modifyRepository.updateTaskDescription(id,desc);
    }

    public void addComment(Long id, String comment){
        modifyRepository.addTaskComment(id,comment);
    }

}
